language: haskell

ghc: 7.8
install:
    - cabal install
script:
    - cabal configure --enable-tests && cabal build && cabal test
notifications:
    email:
      - t.t.mc1192.sf@gmail.com
    on_success: always
    on_failure: always
